# SCREEN SETTINGS
BOARD_ROWS = 25
BOARD_COLS = 50
CELL_SIZE = 20 # pixels per cell
WINDOW_WIDTH = BOARD_COLS * CELL_SIZE
WINDOW_HEIGHT = BOARD_ROWS * CELL_SIZE

# COLORS
GREEN = (34, 139, 34)
BLACK = (0, 0, 0)

# SOLDIER SETTINGS
SOLDIER_ROWS = 4
SOLDIER_COLS = 2
SOLDIER_BODY_ROWS = 3 # the upper part
SOLDIER_FEET_ROWS = 1 # the lower part
SOLDIER_LENGTH = 4 * CELL_SIZE

# FLAG SETTINGS
FLAG_ROWS = 3
FLAG_COLS = 4
FLAG_WIDTH = FLAG_COLS * CELL_SIZE
FLAG_HEIGHT = FLAG_ROWS * CELL_SIZE

# MINES SETTINGS
MINES_COUNT = 20
MINE_ROWS = 1
MINE_COLS = 3
MINE_WIDTH = MINE_COLS * CELL_SIZE
MINE_HEIGHT = MINE_ROWS * CELL_SIZE

# DEFAULT IMAGE SETTINGS
IMAGE_LENGTH = CELL_SIZE * 2

# SLEEP TIMES
MINE_PEEK_COOLDOWN = 3

# SOLDIER STATUS
SOLDIER_REGULAR_IMG = "soldier.png"
SOLDIER_NIGHT_IMG = "soldier_night.png"
SOLDIER_INJURED_IMG = "injury.png"

# GAME OBJECTS IMAGES
GRASS_IMG = "grass.png"
FLAG_IMG = "flag.png"
SNAKE_IMG = "snake.png"
GUARD_IMG = "guard.png"
MINE_IMG = "mine.png"
EXPLOSION_IMG = "explosion.png"
TELEPORT_IMG = "teleport.png"
EMPTY_CELL = ""

FONT_NAME = "Calibri"

# ANIMATION TIMES
ANIMATION_TIME_EXPLOSION = 0.5

# SOLDIER SETTINGS
STEP = 1
X_COORDINATES_INDEX = 0
Y_COORDINATES_INDEX = 1

# FLOOD FILL CONSTS
DFS_SQUARE = "_"
