# SCREEN SETTINGS
BOARD_ROWS = 25
BOARD_COLS = 50
CELL_SIZE = 20 # pixels per cell
WINDOW_WIDTH = BOARD_COLS * CELL_SIZE
WINDOW_HEIGHT = BOARD_ROWS * CELL_SIZE

# SOLDIER SETTINGS
SOLDIER_ROWS = 4
SOLDIER_COLS = 2
SOLDIER_BODY_ROWS = 3 # the upper part
SOLDIER_FEET_ROWS = 1 # the lower part

# COLORS
REGULAR_MODE_COLOR = (34, 139, 34)
NIGHT_MODE_COLOR = (0, 0, 0)

# FLAG SETTINGS
FLAG_ROWS = 3
FLAG_COLS = 4

# MINES SETTINGS
MINES_COUNT = 20
MINE_ROWS = 1
MINE_COLS = 3

# SLEEP TIMES
MINE_PEEK_COOLDOWN = 1

# SOLDIER STATUS
REGULAR_STATUS = "soldier.png"
NIGHT_STATUS = "soldier_night.png"
INJURED_STATUS = "injury.png"

# GAME OBJECTS IMAGES
GRASS_IMG = "grass.png"
FLAG_IMG = "flag.png"
SNAKE_IMG = "snake.png"
GUARD_IMG = "guard.png"
MINE_IMG = "mine.png"
EXPLOSION_IMG = "explosion.png"
TELEPORT_IMG = "teleport.png"
EMPTY_CELL = ""

